README.md
data/config/item-data.json
src/server/game-server.ts
src/server/web-server.ts
src/server/world/config/item-data.ts
src/server/world/world.ts

As well as a rest endpoint for polling the server's game item information.

Adding support for additional item information

---

data/config/item-data-backup.yaml
data/config/item-data.yaml
package-lock.json
package.json
src/world/entity/mob/items/item-container.ts
src/world/entity/mob/player/action/equip-item-action.ts
src/world/entity/mob/player/game-interface.ts
src/world/entity/mob/player/packet/impl/button-click-packet.ts
src/world/entity/mob/player/packet/packet-sender.ts
src/world/entity/mob/player/player-data.ts
src/world/entity/mob/player/player.ts
src/world/entity/mob/walking-queue.ts

Implementing player settings saving/loading/applying and the ability for players to run

Player settings & running

---

src/net/rs-buffer.ts
src/world/config/npc-spawn.ts
src/world/direction.ts
src/world/landscape/modified-landscape-object.ts
src/world/map/chunk-manager.ts
src/world/map/chunk.ts
src/world/map/landscape-object.ts
src/world/mob/npc/npc.ts
src/world/mob/player/action/action.ts
src/world/mob/player/action/door-action.ts
src/world/mob/player/action/input-command-action.ts
src/world/mob/player/packet/impl/object-interaction-packet.ts
src/world/mob/player/packet/impl/walk-packet.ts
src/world/mob/player/packet/incoming-packet-directory.ts
src/world/mob/player/packet/packet-sender.ts
src/world/mob/player/player.ts
src/world/mob/walking-queue.ts
src/world/position.ts
src/world/world.ts

Adds support for:
- Universal single-wide doors!
- Dynamic landscape object adding
- Dynamic landscape object removing
- Player chunk updating (updating for added and removed objects in new chunks while moving between chunks) utilizing the mass-update packet (183)
- Added/removed objects added and removed from collision maps

Doors & landscape objects!

---

src/net/rs-buffer.ts
src/world/mob/player/packet/impl/chat-packet.ts
src/world/mob/player/packet/incoming-packet-directory.ts
src/world/mob/player/player.ts
src/world/mob/player/updating/mob-updating.ts
src/world/mob/player/updating/npc-update-task.ts
src/world/mob/player/updating/player-update-task.ts
src/world/mob/update-flags.ts

Implementing basic player-to-player public chat.

---

package.json
src/game-server.ts
src/plugins/npc-plugin/npc-plugins.ts
src/plugins/object-plugin/object-plugins.ts
src/plugins/plugin-loader.ts
src/world/mob/player/action/npc-action.ts

Improving the plugin system so that you don't need to list every plugin. All plugin files in npc-plugin and object-plugin will be automatically detected and included.

Automagic plugin file detection

---

src/game-server.ts
src/plugins/npc-plugin/hans/hans-plugin.ts
src/world/items/item-container.ts
src/world/mob/mob.ts
src/world/mob/player/action/dialogue-action.ts
src/world/mob/player/game-interface.ts
src/world/mob/player/packet/impl/character-design-packet.ts
src/world/mob/player/packet/packet-sender.ts
src/world/mob/player/player.ts
src/world/mob/skills.ts
src/world/mob/walking-queue.ts
src/world/world.ts

Adding helper methods for checking a mob's inventory or equipment for an item. Also made game screen and chatbox interfaces close when walking if they're marked to do so.

More plugin related quality of life changes 

---

src/plugins/npc-plugin/hans/hans-plugin.ts
src/plugins/object-plugin/doors/door-plugin.ts
src/plugins/object-plugin/doors/double-door-plugin.ts
src/plugins/object-plugin/doors/gate-plugin.ts
src/plugins/object-plugin/trees/tree-plugin.ts
src/world/mob/player/action/action.ts
src/world/mob/player/action/npc-action.ts
src/world/mob/player/action/object-action.ts
src/world/mob/player/player.ts
src/world/mob/walking-queue.ts

Adding support for looping actions, action cancelling, and improving the signature of npc and object action plugins to better future-proof them.

Looping actions + action cancellation 

---

src/plugins/object/cows/cow-plugin.ts
src/plugins/object/doors/double-door-plugin.ts
src/world/mob/player/action/object-action.ts

Cow milking object interaction plugin, and extended the object interaction details to contain the clicked option

Cow milking

---

src/plugins/object/ladders/ladder-plugin.ts

~~it is missing the "climb" action with the chatbox select direction~~

Simple ladder climbing

---

src/plugins/object/mill/hopper-controls-plugin.ts

Hopper controls for lumbridge mill, missing only changing objects for specific player

hopper controls, with grain and flour checking

---

data/config/npc-spawns.yaml
data/config/shops.yaml
src/plugins/npcs/al-kharid/gem-trader-plugin.ts
src/plugins/npcs/bob-plugin.ts
src/world/mob/player/action/buy-item-action.ts
src/world/mob/player/action/buy-item-value-action.ts
src/world/mob/player/action/sell-item-value-action.ts
src/world/mob/player/action/shop-action.ts
src/world/mob/player/packet/impl/item-option-1-packet.ts
src/world/mob/player/widget.ts

1. Shop inventory is now rendering correctly, also when buying items.
2. Added an action for the shop inventory sell option.

Added some small changes to the shop handling.

---

src/plugins/buttons/magic-teleports-plugin.ts
src/plugins/commands/player-graphics-command.ts
src/world/config/animation-ids.ts
src/world/config/gfx-ids.ts
src/world/config/sound-ids.ts

timing, animations, graphics and sound effects 💃

home teleport and player graphics command

---

src/game-server.ts
src/net/incoming-packet-directory.ts
src/net/incoming-packets/item-on-object-packet.ts
src/plugins/items/buckets/empty-container-plugin.ts
src/plugins/items/buckets/fill-container-plugin.ts
src/plugins/items/pots/empty-pot-plugin.ts
src/plugins/objects/cows/cow-plugin.ts
src/plugins/objects/mill/flour-bin-plugin.ts
src/plugins/objects/mill/hopper-controls-plugin.ts
src/plugins/objects/mill/hopper-plugin.ts
src/plugins/objects/pickables/pickables-plugin.ts
src/plugins/plugin.ts
src/world/actor/player/action/item-on-object-action.ts
src/world/config/animation-ids.ts
src/world/config/item-ids.ts
src/world/config/sound-ids.ts

Needs some checking by the lord almight @TheBlackParade

item on object packet, fill water containers, and rest of lumby mill

---

src/plugins/objects/cows/cow-plugin.ts
src/plugins/objects/mill/flour-bin-plugin.ts

needs checking by the almighty @TheBlackParade

set cow plugin and flour bin plugin to use itemonobject

---

src/net/data-parser/client-packet-data-parser.ts
src/net/incoming-packet-directory.ts
src/net/incoming-packets/character-design-packet.ts
src/net/incoming-packets/widgets-closed-packet.ts
src/plugins/dialogue/dialogue-option-plugin.ts
src/plugins/skills/crafting/spinning-wheel-plugin.ts
src/plugins/skills/level-up-dialogue-plugin.ts
src/world/actor/player/action/dialogue-action.ts
src/world/actor/player/action/item-selection-action.ts
src/world/actor/player/player.ts
src/world/actor/skills.ts
src/world/config/widget.ts

Implementing queue-able widgets.

---

src/error-handling.ts
src/game-server.ts
src/main.ts
src/net/data-parser/client-login-parser.ts
src/net/data-parser/login-handshake-parser.ts
src/net/data-parser/update-server-parser.ts
src/net/data-parser/version-handshake-parser.ts
src/plugins/commands/give-item-command.ts
src/plugins/commands/new-dialogue-test-command.ts
src/plugins/npcs/lumbridge/lumbridge-farm-helpers-plugin.ts
src/plugins/objects/ladders/ladder-plugin.ts
src/plugins/quests/cooks-assistant-quest.ts
src/plugins/skills/skill-guide-plugin.ts
src/world/actor/dialogue.ts
src/world/actor/player/action/dialogue-action.ts
src/world/actor/player/action/item-selection-action.ts
src/world/actor/player/player.ts
src/world/config/item-data.ts
src/world/config/npc-spawn.ts
src/world/config/server-config.ts
src/world/config/shops.ts

Adding cleaner error handling for promises.

---

src/plugins/skills/smithing/smelting-plugin.ts
src/util/colors.ts
src/world/config/animation-ids.ts
src/world/config/item-ids.ts
src/world/config/object-ids.ts
src/world/config/sound-ids.ts
src/world/config/widget.ts

Smithing skill

---

src/plugins/skills/skill-guide-plugin.ts

#140 skill guides close on walk

---

src/plugins/npcs/lumbridge/hans-plugin.ts
src/world/actor/player/achievements.ts
src/world/actor/player/player-data.ts
src/world/actor/player/player.ts
src/world/actor/skills.ts

+ `getSkillLevel` function for getting an actor's current level in a given skill, per @Promises 's request.

Achievements

---

src/plugins/commands/give-item-command.ts
src/plugins/commands/spawn-scenery-command.ts
src/plugins/skills/firemaking-plugin.ts
src/world/actor/skills.ts
src/world/world.ts

Also fixes:
- Replaced objects not properly de-registering old/new objects upon replacement and subsequent respawning.
And adds:
- Support for top-level item name searching when using the `give`/`item`/`spawn` command. Uses the `itemIds` config object.

Adding support for selecting player skill info via skill name.

---

data/config/scenery-spawns.yaml
package-lock.json
package.json
src/plugins/items/drop-item-plugin.ts
src/plugins/items/pickup-item-plugin.ts
src/world/skill-util/harvest-skill.ts

Also fixes a minor audit issue and makes woodcutting/mining stop their animation whenever the loop completes.
Stuff requested by @Promises

Making dropping/picking up items cancel other actions in-progress

---

package-lock.json
src/world/actor/player/action/item-selection-action.ts

Also updating the package-lock.json file to fix a vulnerability.

Fixing "Make X" and "Make All" options

---

src/plugins/items/drop-item-plugin.ts

This is exactly how jagex handles it.
also applies to trading, death and staking iirc.

Administators cannot drop items
